// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: souD5h88MhENvTHMTJd8eE
// Component: odXw9sh-TXPn
import * as React from "react"

import { Link, GatsbyLinkProps as LinkProps } from "gatsby"

import * as p from "@plasmicapp/react-web"

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import CommonLandingPage2 from "../../CommonLandingPage2" // plasmic-import: HBZ3E3OXp2Xw/component
import ValuePropListItem from "../../ValuePropListItem" // plasmic-import: eFR6LkfCZMcF/component
import GraphicIcon from "../../GraphicIcon" // plasmic-import: e2aIHUlliT40/component
import Divider from "../../Divider" // plasmic-import: 5YxrxfKmRHtf/component
import SmallValuePropCard from "../../SmallValuePropCard" // plasmic-import: i-nPMUQB3KRp/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen" // plasmic-import: KSAzOQ4LXGzQ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_plasmic_kit_website_components.module.css" // plasmic-import: souD5h88MhENvTHMTJd8eE/projectcss
import * as sty from "./PlasmicAgencies.module.css" // plasmic-import: odXw9sh-TXPn/css

import Icon12Icon from "./icons/PlasmicIcon__Icon12" // plasmic-import: RPhkBowkT3MA/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20" // plasmic-import: 52_x3C6vVI9z/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22" // plasmic-import: o-cOIgwGaem4/icon
import Icon27Icon from "./icons/PlasmicIcon__Icon27" // plasmic-import: Kgv7x1zin2ho/icon
import image87UbX3BvM1DDew from "./images/image87.png" // plasmic-import: UbX3BvM1DDew/picture
import image41PngWlP7VgvsApg from "./images/image41Png.png" // plasmic-import: wl-P7VGVSApg/picture
import image82JH3BsZLhbjIp from "./images/image82.png" // plasmic-import: jH3bsZLhbjIp/picture
import image78DssbWIyYbz from "./images/image78.png" // plasmic-import: dssb-wIY_ybz/picture
import image86YbxRnrbonzGm from "./images/image86.png" // plasmic-import: ybxRnrbonzGm/picture
import image85HTzVezlzn3Nm from "./images/image85.png" // plasmic-import: HTzVEZLZN3NM/picture
import websiteHeroImageTinypngRkxZzCz02F6Z from "./images/websiteHeroImageTinypng.png" // plasmic-import: rkxZZCz02f6z/picture
import imagePyf3PgyY7G from "./images/image.svg" // plasmic-import: _PYF3-PgyY7g/picture
import image3Gx4IdVjRKzbC from "./images/image3.svg" // plasmic-import: GX4idVjRKzbC/picture
import image47DoIhzgdV2Re from "./images/image4.svg" // plasmic-import: 7DoIhzgdV2RE/picture
import image8GirHdEKSi3R from "./images/image8.svg" // plasmic-import: GIRHdE_kSI3r/picture
import image53QOdIcDTdgL6 from "./images/image53.png" // plasmic-import: qOdIC-DTdgL6/picture
import image9YcWQfuPC4T from "./images/image9.svg" // plasmic-import: ycWQfuP-c4-t/picture
import image11JqFnQda2CMp from "./images/image11.svg" // plasmic-import: JqFN-QDA2cMp/picture
import image12MrMuwTQxPQv from "./images/image12.png" // plasmic-import: MrMuwTQxP_QV/picture

export type PlasmicAgencies__VariantMembers = {}

export type PlasmicAgencies__VariantsArgs = {}
type VariantPropType = keyof PlasmicAgencies__VariantsArgs
export const PlasmicAgencies__VariantProps = new Array<VariantPropType>()

export type PlasmicAgencies__ArgsType = {}
type ArgPropType = keyof PlasmicAgencies__ArgsType
export const PlasmicAgencies__ArgProps = new Array<ArgPropType>()

export type PlasmicAgencies__OverridesType = {
  root?: p.Flex<"div">
  commonLandingPage2?: p.Flex<typeof CommonLandingPage2>
  valueA13?: p.Flex<typeof SmallValuePropCard>
  valueA23?: p.Flex<typeof SmallValuePropCard>
  valueA222222?: p.Flex<typeof SmallValuePropCard>
  valueA222?: p.Flex<typeof SmallValuePropCard>
  valueA2322?: p.Flex<typeof SmallValuePropCard>
  valueA22322?: p.Flex<typeof SmallValuePropCard>
}

export interface DefaultAgenciesProps {
  className?: string
}

function PlasmicAgencies__RenderFunc(props: {
  variants: PlasmicAgencies__VariantsArgs
  args: PlasmicAgencies__ArgsType
  overrides: PlasmicAgencies__OverridesType
  dataFetches?: PlasmicAgencies__Fetches
  forNode?: string
}) {
  const { variants, args, overrides, forNode, dataFetches } = props

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants(),
  })

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <CommonLandingPage2
            data-plasmic-name={"commonLandingPage2"}
            data-plasmic-override={overrides.commonLandingPage2}
            children2={
              "Plug into your existing codebase. Use any framework, backend, hosting, CMS, and more."
            }
            className={classNames("__wab_instance", sty.commonLandingPage2)}
            container={
              <React.Fragment>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___5Wi2W)}
                  displayHeight={"52px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: imagePyf3PgyY7G,
                    fullWidth: 300,
                    fullHeight: 126,
                    aspectRatio: 2.374227,
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__r0Ajs)}
                  displayHeight={"40px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: image3Gx4IdVjRKzbC,
                    fullWidth: 300,
                    fullHeight: 76,
                    aspectRatio: 3.968504,
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__qbqHd)}
                  displayHeight={"36px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: image47DoIhzgdV2Re,
                    fullWidth: 300,
                    fullHeight: 79,
                    aspectRatio: 3.785714,
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___5TCbu)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: image8GirHdEKSi3R,
                    fullWidth: 250,
                    fullHeight: 150,
                    aspectRatio: 1.669355,
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hhgh0)}
                  displayHeight={"50px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: image53QOdIcDTdgL6,
                    fullWidth: 670,
                    fullHeight: 195,
                    aspectRatio: undefined,
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dv9Cv)}
                  displayHeight={"32px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: image9YcWQfuPC4T,
                    fullWidth: 300,
                    fullHeight: 82,
                    aspectRatio: 3.675,
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__wVsFb)}
                  displayHeight={"28px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: image11JqFnQda2CMp,
                    fullWidth: 300,
                    fullHeight: 68,
                    aspectRatio: 4.441718,
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__h7NjL)}
                  displayHeight={"26px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={{
                    src: image12MrMuwTQxPQv,
                    fullWidth: 2600,
                    fullHeight: 623,
                    aspectRatio: undefined,
                  }}
                />
              </React.Fragment>
            }
            slot={
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__u1Rgy
                )}
              >
                <span className={"plasmic_default__all plasmic_default__span"}>
                  <React.Fragment>
                    {"Build engaging digital experiences ⚡️ "}
                  </React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontStyle: "italic" }}
                  >
                    {"fast"}
                  </span>
                  <React.Fragment>{"."}</React.Fragment>
                </span>
              </div>
            }
            slot2={
              "The web design tool that works seamlessly with your tech stack. The visual CMS that clients love."
            }
            slot3={
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__vYlbh)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__wR7P6)}
                >
                  <SmallValuePropCard
                    data-plasmic-name={"valueA13"}
                    data-plasmic-override={overrides.valueA13}
                    actionButton={null}
                    description={null}
                    followupLink={null}
                    icon={null}
                    ltr={"ltr" as const}
                    showcaseImage={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__oioBc)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: image87UbX3BvM1DDew,
                          fullWidth: 590,
                          fullHeight: 300,
                          aspectRatio: undefined,
                        }}
                      />
                    }
                  >
                    {"Landing pages"}
                  </SmallValuePropCard>

                  <SmallValuePropCard
                    data-plasmic-name={"valueA23"}
                    data-plasmic-override={overrides.valueA23}
                    actionButton={null}
                    className={classNames("__wab_instance", sty.valueA23)}
                    description={null}
                    followupLink={null}
                    icon={null}
                    ltr={"ltr" as const}
                    showcaseImage={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__sbi4E)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: image41PngWlP7VgvsApg,
                          fullWidth: 583,
                          fullHeight: 428,
                          aspectRatio: undefined,
                        }}
                      />
                    }
                  >
                    {"Conversion pages"}
                  </SmallValuePropCard>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__jgl2K)}
                >
                  <SmallValuePropCard
                    data-plasmic-name={"valueA222222"}
                    data-plasmic-override={overrides.valueA222222}
                    actionButton={null}
                    className={classNames("__wab_instance", sty.valueA222222)}
                    description={null}
                    followupLink={null}
                    icon={null}
                    ltr={"ltr" as const}
                    showcaseImage={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___88MTf)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: image82JH3BsZLhbjIp,
                          fullWidth: 435,
                          fullHeight: 204,
                          aspectRatio: undefined,
                        }}
                      />
                    }
                  >
                    {"Announcement bars"}
                  </SmallValuePropCard>

                  <SmallValuePropCard
                    data-plasmic-name={"valueA222"}
                    data-plasmic-override={overrides.valueA222}
                    actionButton={null}
                    className={classNames("__wab_instance", sty.valueA222)}
                    description={null}
                    followupLink={null}
                    icon={null}
                    ltr={"ltr" as const}
                    showcaseImage={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__rSXt5)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: image78DssbWIyYbz,
                          fullWidth: 452,
                          fullHeight: 250,
                          aspectRatio: undefined,
                        }}
                      />
                    }
                  >
                    {"Offer overlays"}
                  </SmallValuePropCard>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__dGdyT)}
                >
                  <SmallValuePropCard
                    data-plasmic-name={"valueA2322"}
                    data-plasmic-override={overrides.valueA2322}
                    actionButton={null}
                    className={classNames("__wab_instance", sty.valueA2322)}
                    description={null}
                    followupLink={null}
                    icon={null}
                    ltr={"ltr" as const}
                    showcaseImage={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__kRc7)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: image86YbxRnrbonzGm,
                          fullWidth: 432,
                          fullHeight: 164,
                          aspectRatio: undefined,
                        }}
                      />
                    }
                  >
                    {"Heroes"}
                  </SmallValuePropCard>

                  <SmallValuePropCard
                    data-plasmic-name={"valueA22322"}
                    data-plasmic-override={overrides.valueA22322}
                    actionButton={null}
                    className={classNames("__wab_instance", sty.valueA22322)}
                    description={null}
                    followupLink={null}
                    icon={null}
                    ltr={"ltr" as const}
                    showcaseImage={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__cJmbf)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: image85HTzVezlzn3Nm,
                          fullWidth: 596,
                          fullHeight: 226,
                          aspectRatio: undefined,
                        }}
                      />
                    }
                  >
                    {"Promotional sections"}
                  </SmallValuePropCard>
                </p.Stack>
              </p.Stack>
            }
            slot4={
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__fWdj)}
              >
                <ValuePropListItem
                  slot={
                    <GraphicIcon
                      className={classNames(
                        "__wab_instance",
                        sty.graphicIcon__sTeBf
                      )}
                      colors={"lightBlueSolid" as const}
                    >
                      <Icon12Icon
                        className={classNames(defaultcss.all, sty.svg__kqyPq)}
                        role={"img"}
                      />
                    </GraphicIcon>
                  }
                  slot2={"No-code autonomy."}
                >
                  {
                    "Easy-to-use but powerful drag-and-drop builder to create web experiences incredibly fast."
                  }
                </ValuePropListItem>

                <Divider
                  className={classNames("__wab_instance", sty.divider__ugzge)}
                />

                <ValuePropListItem
                  slot={
                    <GraphicIcon
                      className={classNames(
                        "__wab_instance",
                        sty.graphicIcon__btYh1
                      )}
                      colors={"lightBlueSolid" as const}
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg___7CHoD)}
                        role={"img"}
                      />
                    </GraphicIcon>
                  }
                  slot2={"Limitless speed."}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___2LBxg
                    )}
                  >
                    {"The only WYSIWYG builder that never limits you."}
                  </div>
                </ValuePropListItem>

                <Divider
                  className={classNames("__wab_instance", sty.divider__eiKu)}
                />

                <ValuePropListItem
                  slot={
                    <GraphicIcon
                      className={classNames(
                        "__wab_instance",
                        sty.graphicIcon__dfcVn
                      )}
                      colors={"lightBlueSolid" as const}
                    >
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg__jHurl)}
                        role={"img"}
                      />
                    </GraphicIcon>
                  }
                  slot2={"Free up developers."}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__vu1Ku
                    )}
                  >
                    {
                      "Empower content editors and designers. Let developers focus on code rather than pixel-pushing."
                    }
                  </div>
                </ValuePropListItem>

                <Divider
                  className={classNames("__wab_instance", sty.divider__uwGdg)}
                />

                <ValuePropListItem
                  slot={
                    <GraphicIcon
                      className={classNames(
                        "__wab_instance",
                        sty.graphicIcon__wMyNp
                      )}
                      colors={"lightBlueSolid" as const}
                    >
                      <Icon27Icon
                        className={classNames(defaultcss.all, sty.svg__aa4Pb)}
                        role={"img"}
                      />
                    </GraphicIcon>
                  }
                  slot2={"Hit the ground running."}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__kZvmY
                    )}
                  >
                    {
                      "Use your existing design system, import from Figma, or grab our templates."
                    }
                  </div>
                </ValuePropListItem>
              </p.Stack>
            }
            slot6={
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__h8Te)}
                displayHeight={"auto" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"1200px" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"100%" as const}
                src={{
                  src: websiteHeroImageTinypngRkxZzCz02F6Z,
                  fullWidth: 1292,
                  fullHeight: 736,
                  aspectRatio: undefined,
                }}
              />
            }
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__yueTw
              )}
            >
              {"Move fast. Grow faster."}
            </div>
          </CommonLandingPage2>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null
}

const PlasmicDescendants = {
  root: [
    "root",
    "commonLandingPage2",
    "valueA13",
    "valueA23",
    "valueA222222",
    "valueA222",
    "valueA2322",
    "valueA22322",
  ],
  commonLandingPage2: [
    "commonLandingPage2",
    "valueA13",
    "valueA23",
    "valueA222222",
    "valueA222",
    "valueA2322",
    "valueA22322",
  ],
  valueA13: ["valueA13"],
  valueA23: ["valueA23"],
  valueA222222: ["valueA222222"],
  valueA222: ["valueA222"],
  valueA2322: ["valueA2322"],
  valueA22322: ["valueA22322"],
} as const
type NodeNameType = keyof typeof PlasmicDescendants
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number]
type NodeDefaultElementType = {
  root: "div"
  commonLandingPage2: typeof CommonLandingPage2
  valueA13: typeof SmallValuePropCard
  valueA23: typeof SmallValuePropCard
  valueA222222: typeof SmallValuePropCard
  valueA222: typeof SmallValuePropCard
  valueA2322: typeof SmallValuePropCard
  valueA22322: typeof SmallValuePropCard
}

type ReservedPropsType = "variants" | "args" | "overrides"
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAgencies__OverridesType,
  DescendantsType<T>
>
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAgencies__VariantsArgs
    args?: PlasmicAgencies__ArgsType
    overrides?: NodeOverridesType<T>
    dataFetches?: PlasmicAgencies__Fetches
  } & Omit<PlasmicAgencies__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAgencies__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key }
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAgencies__ArgProps,
      internalVariantPropNames: PlasmicAgencies__VariantProps,
    })

    const { dataFetches } = props

    return PlasmicAgencies__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicAgencies"
  } else {
    func.displayName = `PlasmicAgencies.${nodeName}`
  }
  return func
}

export const PlasmicAgencies = Object.assign(
  // Top-level PlasmicAgencies renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    commonLandingPage2: makeNodeComponent("commonLandingPage2"),
    valueA13: makeNodeComponent("valueA13"),
    valueA23: makeNodeComponent("valueA23"),
    valueA222222: makeNodeComponent("valueA222222"),
    valueA222: makeNodeComponent("valueA222"),
    valueA2322: makeNodeComponent("valueA2322"),
    valueA22322: makeNodeComponent("valueA22322"),

    // Metadata about props expected for PlasmicAgencies
    internalVariantProps: PlasmicAgencies__VariantProps,
    internalArgProps: PlasmicAgencies__ArgProps,
  }
)

export default PlasmicAgencies
/* prettier-ignore-end */
